import saveAs from 'file-saver';
import { TranscriptItem } from '../types/transcript';
import { MeetingSession } from '../types/meeting';

export function exportToTxt(session: Partial<MeetingSession>, transcripts: TranscriptItem[]) {
  const fileName = `Transkrip_Meeting_${session.title?.replace(/[^a-zA-Z0-9]/g, '_') || 'Session'}_${new Date().toISOString().slice(0, 10)}.txt`;

  const minutes = Math.floor((session.elapsedSeconds || 0) / 60);
  const seconds = (session.elapsedSeconds || 0) % 60;
  const durationStr = `${minutes}m ${seconds}s`;

  let content = "====================================================================\n";
  content += "                   TRANSKRIP RESMI SESI MEETING                     \n";
  content += "      Generated by AI Meeting Bot Controller (Deepgram Nova-2)       \n";
  content += "====================================================================\n\n";
  content += `Topik Meeting   : ${session.title || 'Meeting Tanpa Judul'}\n`;
  content += `Platform / URL  : ${session.platform?.toUpperCase() || 'GOOGLE MEET'} (${session.url || '-'})\n`;
  content += `Tanggal Sesi    : ${new Date().toLocaleDateString('id-ID', { dateStyle: 'full' })}\n`;
  content += `Durasi Rekaman  : ${durationStr}\n`;
  content += `Keamanan Jaringan: VPN Perusahaan (${session.vpnIp || '10.24.0.12'})\n`;
  content += `Total Transkrip : ${transcripts.length} entri percakapan\n\n`;
  content += "----------------------- LOG PERCAKAPAN -----------------------------\n\n";

  transcripts.forEach((t) => {
    const langTag = t.language === 'mixed' ? '[MIXED]' : `[${t.language.toUpperCase()}]`;
    content += `[${t.timestamp}] ${t.speaker} ${langTag}:\n`;
    content += `${t.text}\n\n`;
  });

  content += "====================================================================\n";
  content += "                         AKHIR DOKUMEN                              \n";
  content += "====================================================================\n";

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, fileName);
}
